-- GENERATED by scripts/gen_dbt_sources.py from generator/models.py — do not edit; run `make gen-sources`.
create schema if not exists raw;
create table if not exists raw.events (
    insert_id varchar not null,
    event_type varchar not null,
    user_id varchar not null,
    device_id varchar not null,
    client_event_time timestamp not null,
    server_received_time timestamp not null,
    server_upload_time timestamp not null,
    event_properties json not null
);
create table if not exists raw.dim_user (
    user_id varchar not null,
    tz varchar not null,
    cohort_id varchar not null,
    signup_date date not null,
    valid_from timestamp not null,
    valid_to timestamp
);
