"""`make gen-sources`: render the raw DDL and dbt `sources.yml` from the
pydantic contract (generator/models.py → Event, DimUserRow).

Tooling, not pipeline code: it imports `generator.models`, whose other record
types the pipeline may not name; its OUTPUT names only the two raw tables.
Writes `loader/ddl.sql`, `dbt/models/staging/sources.yml` and (Phase 9b) the
BigQuery landing schema `loader/bq_schema.json`; with `--check`,
renders to memory and exits 1 if either committed file differs
(tests/test_dbt_sources.py is the same check in-process)."""

from __future__ import annotations

import argparse
import json
import sys
import types
import typing
from datetime import date, datetime
from enum import StrEnum
from pathlib import Path

from pydantic import BaseModel

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))  # `uv run python scripts/x.py`: repo not on sys.path
from generator.models import DimUserRow, Event  # noqa: E402

DDL_PATH = ROOT / "loader" / "ddl.sql"
SOURCES_PATH = ROOT / "dbt" / "models" / "staging" / "sources.yml"
BQ_SCHEMA_PATH = ROOT / "loader" / "bq_schema.json"  # the second dialect (Phase 9b)
HEADER = (
    "GENERATED by scripts/gen_dbt_sources.py from generator/models.py"
    " — do not edit; run `make gen-sources`."
)

# (dbt source table name, pydantic model). Order is output order.
TABLES: list[tuple[str, type[BaseModel]]] = [
    ("events", Event),
    ("dim_user", DimUserRow),
]
SCHEMA = "raw"


def _unwrap(annotation: object) -> tuple[object, bool]:
    """(inner type, optional?) — `X | None` → (X, True)."""
    if typing.get_origin(annotation) in (types.UnionType, typing.Union):
        args = [a for a in typing.get_args(annotation) if a is not type(None)]
        if len(args) == 1:
            return args[0], True
    return annotation, False


def duckdb_type(annotation: object) -> str:
    inner, _ = _unwrap(annotation)
    if isinstance(inner, type) and issubclass(inner, StrEnum):
        return "varchar"
    if inner is str:
        return "varchar"
    if inner is datetime:
        return "timestamp"
    if inner is date:
        return "date"
    if typing.get_origin(inner) is dict or inner is dict:
        return "json"
    raise TypeError(f"no DuckDB type for {annotation!r}")


# DuckDB type → BigQuery type (the landing's explicit load schema, Phase 9b).
# `json` → JSON keeps a JSON null a JSON null; timestamps are UTC instants.
BQ_TYPES = {
    "varchar": "STRING",
    "timestamp": "TIMESTAMP",
    "date": "DATE",
    "json": "JSON",
}


def columns(model: type[BaseModel]) -> list[tuple[str, str, bool, list[str] | None]]:
    """(name, duckdb type, nullable, accepted values) per field, in field order."""
    out = []
    for name, field in model.model_fields.items():
        inner, optional = _unwrap(field.annotation)
        values = None
        if isinstance(inner, type) and issubclass(inner, StrEnum):
            values = [m.value for m in inner]
        out.append((name, duckdb_type(field.annotation), optional, values))
    return out


def column_tests(nullable: bool, values: list[str] | None) -> list[str]:
    """dbt data tests per column: not_null unless Optional; accepted_values for
    an enum. Never `unique` — the export carries duplicate insert_ids by
    contract; uniqueness is a staging test."""
    tests: list[str] = []
    if not nullable:
        tests.append("not_null")
    if values is not None:
        vals = ", ".join(f'"{v}"' for v in values)
        tests.append(f"accepted_values:\n  arguments:\n    values: [{vals}]")
    return tests


def render_ddl() -> str:
    lines = [f"-- {HEADER}", f"create schema if not exists {SCHEMA};"]
    for table, model in TABLES:
        lines.append(f"create or replace table {SCHEMA}.{table} (")
        cols = columns(model)
        for i, (name, typ, nullable, _) in enumerate(cols):
            null = "" if nullable else " not null"
            comma = "," if i < len(cols) - 1 else ""
            lines.append(f"    {name} {typ}{null}{comma}")
        lines.append(");")
    return "\n".join(lines) + "\n"


def render_bq_schema() -> str:
    """`{table: [{name, type, mode}, …]}` — the BigQuery load schema per raw
    table (google.cloud.bigquery.SchemaField's fields), `REQUIRED` unless
    Optional. The file carries the header as a `_comment` key: JSON has none."""
    out: dict[str, object] = {"_comment": HEADER}
    for table, model in TABLES:
        out[table] = [
            {
                "name": name,
                "type": BQ_TYPES[typ],
                "mode": "NULLABLE" if nullable else "REQUIRED",
            }
            for name, typ, nullable, _ in columns(model)
        ]
    return json.dumps(out, indent=2) + "\n"


def render_sources() -> str:
    lines = [
        f"# {HEADER}",
        "version: 2",
        "",
        "sources:",
        f"  - name: {SCHEMA}",
        f"    schema: {SCHEMA}",
        "    description: Raw landing — the Amplitude export shape and the dim seed"
        " file, loaded by `make load` (DuckDB) / `make bq-load` (BigQuery)."
        " No freshness config (it reads the clock).",
        "    tables:",
    ]
    for table, model in TABLES:
        doc = (model.__doc__ or "").splitlines()[0]
        lines += [
            f"      - name: {table}",
            f"        description: {doc}",
        ]
        if table == "dim_user":
            # Phase 10: the §3.3 source swap. Default = the landed table
            # (every existing build unchanged); the Spanner integration run
            # overrides it to the federation view `dim_user_spanner`.
            lines.append(
                "        identifier: \"{{ var('dim_user_identifier', 'dim_user') }}\""
            )
        lines.append("        columns:")
        for name, typ, nullable, values in columns(model):
            desc = f"{typ}, nullable" if nullable else typ
            lines += [f"          - name: {name}", f"            description: {desc}"]
            tests = column_tests(nullable, values)
            if tests:
                lines.append("            data_tests:")
                for t in tests:
                    first, *rest = t.split("\n")
                    lines.append(f"              - {first}")
                    lines += [f"                {r}" for r in rest]
    return "\n".join(lines) + "\n"


# Phase 10: the Spanner dims shapes, rendered from the SAME contract. Not
# files `make gen-sources` writes — they are PINNED inside
# infra/modules/spanner/main.tf (tf-freeze's manifest pins *.tf only, so a
# side file could drift under the frozen tree): tests/test_dbt_sources.py
# fails when the .tf drifts from these renders, and the repair is to paste
# the render into the .tf by hand (then `make tf-freeze CONFIRM=yes`).
SPANNER_TYPES = {"varchar": "string(max)", "timestamp": "timestamp", "date": "date"}
SPANNER_CONNECTION = "spanner_dims"


def spanner_dim_user_ddl() -> str:
    """The Spanner `dim_user` DDL (SCD2 — key (user_id, valid_from), §2.3)."""
    cols = columns(DimUserRow)
    lines = ["create table dim_user ("]
    for i, (name, typ, nullable, _) in enumerate(cols):
        null = "" if nullable else " not null"
        comma = "," if i < len(cols) - 1 else ""
        lines.append(f"    {name} {SPANNER_TYPES[typ]}{null}{comma}")
    lines.append(") primary key (user_id, valid_from)")
    return "\n".join(lines)


def federation_view_sql() -> str:
    """The `raw.dim_user_spanner` view body: EXTERNAL_QUERY over the Spanner
    connection, one column per line, each CAST to the generated BigQuery
    landing schema's type (the same map `bq_schema.json` is rendered from —
    so the view's shape is the landed table's by construction, not by
    Spanner's type map, a named stack risk), the exact text the .tf embeds
    (the `${var.*}` placeholders are Terraform's, rendered at apply)."""
    cols = columns(DimUserRow)
    names = [c[0] for c in cols]
    inner = f"select {', '.join(names)} from dim_user"
    body = ",\n".join(
        f"    cast({name} as {BQ_TYPES[typ].lower()}) as {name}"
        for name, typ, _, _ in cols
    )
    return (
        "select\n"
        f"{body}\n"
        "from external_query(\n"
        "    'projects/${var.project_id}/locations/${var.region}"
        f"/connections/{SPANNER_CONNECTION}',\n"
        f"    '{inner}'\n"
        ")"
    )


def render() -> dict[Path, str]:
    return {
        DDL_PATH: render_ddl(),
        SOURCES_PATH: render_sources(),
        BQ_SCHEMA_PATH: render_bq_schema(),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    rendered = render()
    stale = [p for p, s in rendered.items() if not p.exists() or p.read_text() != s]
    if a.check:
        for p in stale:
            print(f"gen-sources STALE: {p.name}")
        verdict = "OK" if not stale else "FAIL"
        print(f"gen-sources {verdict}: {len(rendered)} files, {len(stale)} stale")
        return 1 if stale else 0
    for p, s in rendered.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(s)
    print(f"gen-sources OK: {len(rendered)} files, {len(stale)} stale")
    return 0


if __name__ == "__main__":
    sys.exit(main())
